
# Config
permalink: /:title
url: http://cassielear.com
relativeUrl: /

# Metadata
title: Cassie Lear | Flutist
description: "Cassie Lear</strong> is an active flute performer and teacher in the Seattle area. Cassie teaches at a studio located in the Greenwood neighborhood in Seattle and is the flute teacher at the Happy Minds School of Music in Bellevue. She performs as part of the flute duo Novantika, playing music from the Renaissance to today."

# Analytics
analytics: tkjmtedw39
